[package]
name = "zero_shell"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.41"
colored = "3.0.0"
libc = "0.2.174"
terminal_size = "0.4.2"
users = "0.11.0"
